version: '2'
services:
  postgres:
    container_name: postgres
    image: postgres:9.5
    ports:
      - 5432:5432
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    driver: local
