# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 14:32
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('repeat', models.CharField(default=3, max_length=255)),
                ('weight', models.FloatField()),
                ('rest_time', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SetExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='exercise',
            name='set_exercise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.SetExercise'),
        ),
    ]
