# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 15:07
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='example_photo',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to=''),
        ),
    ]
