# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 20:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_exercise_example_photo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SetExercise',
            new_name='GroupExercise',
        ),
    ]
