# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-04 21:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_auto_20160905_0004'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exercise',
            unique_together=set([('title', 'training')]),
        ),
        migrations.AlterUniqueTogether(
            name='label',
            unique_together=set([('title', 'owner')]),
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together=set([('title', 'owner')]),
        ),
    ]
