# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 21:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20160530_2358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercise',
            old_name='set_exercise',
            new_name='group_exercise',
        ),
    ]
