# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-27 00:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0003_auto_20160905_0008'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['priority']},
        ),
        migrations.AddField(
            model_name='training',
            name='sequence_priority',
            field=models.IntegerField(default=1),
        ),
    ]
