# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-30 22:08
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0004_auto_20160531_0001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='example_photo',
            field=sorl.thumbnail.fields.ImageField(default=None, upload_to='exercise'),
        ),
    ]
