# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-31 15:03
from __future__ import unicode_literals

from django.db import migrations
import imagekit.models.fields
import workout.tools


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0006_auto_20160531_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='example_photo',
            field=imagekit.models.fields.ProcessedImageField(default=None, upload_to=workout.tools.upload_to_id_image),
        ),
    ]
