# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 19:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0007_auto_20160531_1803'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GroupExercise',
            new_name='Training',
        ),
        migrations.RenameField(
            model_name='exercise',
            old_name='group_exercise',
            new_name='training'
        ),
    ]
