# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 00:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0010_auto_20160611_0321'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='label',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainings', to='workout.Label'),
        ),
    ]
