# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 10:28
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0011_training_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='label',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='training',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
