# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-11 10:32
from __future__ import unicode_literals

import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    LabelModel = apps.get_model('workout', 'Label')
    for row in LabelModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save()

    ExerciseModel = apps.get_model('workout', 'Exercise')
    for row in ExerciseModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save()

    TrainingModel = apps.get_model('workout', 'Training')
    for row in TrainingModel.objects.all():
        row.uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0012_auto_20160611_1328'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
